### ISSUE TITLE
appending to incorrect display

### ISSUE THREAD

**Issue by JMankewitz** [rholson1/tobii_calibration#1]
Hey! We're troubleshooting - trying to keep in one place and GH works best. 

We're trying to change the display of the calibration screen, and it only sends to Display 1, not display 2. It seems that the screen is correct when we print screen 

```
Monitor(x=0, y=0, width=1920, height=1080, width_mm=509, height_mm=286, name='\\\\.\\DISPLAY2', is_primary=True)
```

But it's still sending to DISPLAY1.

**Comment by rholson1** [comment]
Are you using the latest version?  Line 299 should be:
`self.calib_window.overrideredirect(True)`
